### ISSUE TITLE
Error: No plugin init file detected (extensionless init files)

### ISSUE THREAD

**Issue by jackbow** [mattmc3/antidote#101]
When running `antidote load` with `ohmyzsh/ohmyzsh path:plugins/fd` in my `zsh_plugins.txt` file I get the error:
```
antidote: no plugin init file detected in '/Users/jb/Library/Caches/antidote/https-COLON--SLASH--SLASH-github.com-SLASH-ohmyzsh-SLASH-ohmyzsh/plugins/fd'.
```
It must not be detecting the _fd file as an init file. Perhaps we can check for extensionless files as init files ([via something like this?](https://unix.stackexchange.com/a/144209))
Link to folder on github: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/fd

**Comment by mattmc3** [comment]
Antidote is behaving as expected. There's no actual plugin file in that folder. You probably wanted this syntax instead: `ohmyzsh/ohmyzsh path:plugins/fd kind:fpath`.
