### ISSUE TITLE
'antidote -v' still shows previous version after running 'antidote update'

### ISSUE THREAD

**Issue by manfred3000** [mattmc3/antidote#116]
After presumably updating to Version 1.8.2 `antidote` reports it's still running Version 1.8.1

Some directories inside `~/.antidote` have been updated, `.bumpversion.cfg `apparently has not.

`zsh` is behaving normally and all plugins are active - so no issues apart from not knowing whether the update was successful.

**Comment by mattmc3** [comment]
Good catch. Thanks. I've cut a new release.
