### ISSUE TITLE
Does it make sense to move ~/.antidote to $XDG_CACHE_HOME/antidote ?

### ISSUE THREAD

**Issue by eggbean** [mattmc3/antidote#129]
I'm quite a new user to antidote, so I am not sure if it makes sense to move ~/.antidote to $XDG_CACHE_HOME/antidote. It's not a directory that needs to be easily accessible by the user, is it?

I don't want to move it to $ZDOTDIR as I haven't set it.

**Comment by mattmc3** [comment]
I leave my `$ANTIDOTE_HOME` in $XDG_CACHE_HOME. It's not a user directory, no. My recommendation is let antidote manage repos in the default cache location, and store your custom plugins in $ZDOTDIR, but let antidote load them.

**Comment by eggbean** [comment]
> ...and also let antidote manage itself there too. My recommendation is let antidote manage itself and repos in the default cache location...

Thanks. Do I have to do anything in particular to have antidote manage itself? I'm not sure what you mean by that.

**Comment by mattmc3** [comment]
I just mean using `antidote update` for self updates.

**Comment by eggbean** [comment]
I have a script which installs and updates everything that needs installing or updating and I have this included in it:

```
# Setup/update antidote
if [[ $ZSH_VERSION ]]; then
  if [[ ! -d ~/.cache/antidote ]]; then
    git clone --depth=1 https://github.com/mattmc3/antidote.git \
      ~/.cache/antidote
  fi
  source ~/.cache/antidote/antidote.zsh
  antidote load ~/.dotfiles/config/.includes/zsh_plugins.txt
  antidote update
fi
```
This is in my `.zshrc`:

```
# Load antidote
if [[ -d ~/.cache/antidote ]]; then
  source ~/.cache/antidote/antidote.zsh
  antidote load ~/.dotfiles/config/.includes/zsh_plugins.txt
fi
```
This has been working fine, but I deleted `~/.cache/antidote` to see what would happen on a new host and I get these errors when I run the update script:

```
/home/jason/.dotfiles/config/.includes/zsh_plugins.zsh:source:2: no such file or directory: /home/jason/.cache/antidote/https-COLON--SLASH--SLASH-github.com-SLASH-Tarrasch-SLASH-zsh-bd/bd.plugin.zsh
/home/jason/.dotfiles/config/.includes/zsh_plugins.zsh:source:4: no such file or directory: /home/jason/.cache/antidote/https-COLON--SLASH--SLASH-github.com-SLASH-jirutka-SLASH-zsh-shift-select/zsh-shift-select.plugin.zsh
/home/jason/.dotfiles/config/.includes/zsh_plugins.zsh:source:6: no such file or directory: /home/jason/.cache/antidote/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-completions/zsh-completions.plugin.zsh
/home/jason/.dotfiles/config/.includes/zsh_plugins.zsh:source:8: no such file or directory: /home/jason/.cache/antidote/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
/home/jason/.dotfiles/config/.includes/zsh_plugins.zsh:source:10: no such file or directory: /home/jason/.cache/antidote/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-syntax-highlighting/zsh-syntax-highlighting.plugin.zsh
```
Why aren't the plugins being reinstalled? Thanks.

**Comment by mattmc3** [comment]
The new 1.8.7 release should handle this edge case now.
