### ISSUE TITLE
Nix package?

### ISSUE THREAD

**Issue by mcdent** [mattmc3/antidote#130]
Hey, I wonder if its possible for anybody to build a nix package of Antidote?
I was able to use a nix package of Antibody but I noticed it is no longer maintained. Also the package of Antibody
is marked as failed on MacOS/Darwin.
Not sure I am skilled enough to carry this out myself! Thanks.

**Comment by hitsmaxft** [comment]
antidote is available in nixpkgs.antidote 

you may need the home-manager to manager configuration
or mannualy import

add here to your nix script that build .zshrc
```nix
source ${pkg.antidote}share/antidote/antidote.zsh 
```

**Comment by mattmc3** [comment]
Merged this PR. Thanks @hitsmaxft.
