### ISSUE TITLE
How to use ztyle configuration for omz ssh-agent plugin

### ISSUE THREAD

**Issue by codevbus** [mattmc3/antidote#135]
I cannot figure out how to get a working invocation for

` zstyle :omz:plugins:ssh-agent agent-forwarding yes`

**Comment by mattmc3** [comment]
Can you share your `.zsh_plugins.txt`?

**Comment by codevbus** [comment]
```
`#!/usr/local/bin/zsh

ohmyzsh/ohmyzsh path:plugins/ssh-agent
romkatv/powerlevel10k

mattmc3/zephyr path:plugins/completion
belak/zsh-utils path:history

mattmc3/zfunctions
zsh-users/zsh-autosuggestions
zdharma-continuum/fast-syntax-highlighting kind:defer
zsh-users/zsh-history-substring-search
`
``

**Comment by codevbus** [comment]
````#!/usr/local/bin/zsh

ohmyzsh/ohmyzsh path:plugins/ssh-agent
romkatv/powerlevel10k

mattmc3/zephyr path:plugins/completion
belak/zsh-utils path:history

mattmc3/zfunctions
zsh-users/zsh-autosuggestions
zdharma-continuum/fast-syntax-highlighting kind:defer
zsh-users/zsh-history-substring-search
```

**Comment by codevbus** [comment]
`#!/usr/local/bin/zsh

ohmyzsh/ohmyzsh path:plugins/ssh-agent
romkatv/powerlevel10k

mattmc3/zephyr path:plugins/completion
belak/zsh-utils path:history

mattmc3/zfunctions
zsh-users/zsh-autosuggestions
zdharma-continuum/fast-syntax-highlighting kind:defer
zsh-users/zsh-history-substring-search
`

**Comment by mattmc3** [comment]
And is the relevant part of your `.zshrc` essentially this?

```zsh
zstyle ':omz:plugins:ssh-agent' agent-forwarding 'yes'
source /path/to/antidote.zsh
antidote load ${ZDOTDIR:-$HOME}/.zsh_plugins.txt
```

**Comment by codevbus** [comment]
I just have these directives:

```
zstyle ':antidote:bundle' use-friendly-names on
zstyle ':ohmyzsh:plugins:ssh-agent' agent-forwarding yes identities id_rsa git_rsa
```

**Comment by mattmc3** [comment]
You'll need to set all your zstyles before running `antidote load`. Otherwise the plugins will get sourced without those configs in place.

https://github.com/ohmyzsh/ohmyzsh/blob/master/plugins/ssh-agent/ssh-agent.plugin.zsh

**Comment by codevbus** [comment]
Sorry for the late follow up. I have the correct order now, but I'm still unsure how to correctly pass options to the ssh-agent. The stanza I have there is not effective.

**Comment by mattmc3** [comment]
I think you're a bit outside the scope of antidote support at this point, since antidote is working as expected and we're in the internals of an actual plugin. I'm not a user of that particular OMZ plugin, and you'll probably get better help from the Oh-My-Zsh team on it. One thing I did notice is that you are using the P10k prompt, but aren't using the recommended P10k zstyles for that plugin: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/ssh-agent#powerline-10k-specific-settings

Best of luck.
