### ISSUE TITLE
Doesn't seem to work with mnowotnik/fzshell

### ISSUE THREAD

**Issue by eggbean** [mattmc3/antidote#136]
I tried this [mnowotnik/fzshell](https://github.com/mnowotnik/fzshell) plugin, which only mentions support for zplug.

I added it to `zsh_plugins.txt` as `mnowotnik/fzshell`.

I'm not sure how to use it, but when I type `docker rmi` and then type `ctrl-n` I get this error:

`fzshell_widget:3: no such file or directory: /home/jason/.cache/antidote/https-COLON--SLASH--SLASH-github.com-SLASH-mnowotnik-SLASH-fzshell/fzshell`

**Comment by mattmc3** [comment]
Yes - tracking it here: https://github.com/mattmc3/antidote/issues/12
