### ISSUE TITLE
Setup and primary script will not execute

### ISSUE THREAD

**Issue by andyfore** [mattmc3/antidote#138]
I am trying to use antidote on my account at work and I get the following errors after executing the shell:

```
/home/afore/.local/antidote/antidote.zsh:11: command not found: __antidote_setup
/home/afore/.zshrc:40: command not found: antidote
```

The section of my .zshrc file loading antidote is:

```
# source antidote
source $HOME/.local/antidote/antidote.zsh

# initialize plugins statically with ${ZDOTDIR:-~}/.zsh_plugins.txt
antidote load
```
Here is my path:

```
[afore@scooby4]~% echo $PATH
/opt/rh/rh-git29/root/usr/bin:/usr/local/scripts:/home/afore/local/bin:/home/afore/.local/bin:/usr/local/bin:/usr/bin:/home/afore/bin:/usr/local/sbin:/usr/sbin
```

**Comment by mattmc3** [comment]
Hey @andyfore. Thanks for using antidote. I'm not sure exactly how, but my best guess at what's happening is that your antidote install isn't correct somehow or has gotten messed up. Have you tried removing and cloning again?

```zsh
rm -rf -- $HOME/.local/antidote
git clone --depth=1 https://github.com/mattmc3/antidote.git $HOME/.local/antidote
```

If you aren't comfortable with removing (`rm`), you could change that line to make a backup instead `mv  $HOME/.local/antidote  $HOME/.local/antidote.bak`. Then reload zsh.

> Here is my path:

antidote is implemented as a Zsh function, so your path won't matter in successfully running antidote.

Let me know if this helps.

**Comment by andyfore** [comment]
No dice.  I even downloaded the archive of the repo instead of using git to clone it.  I still get the same error.  When I turn on verbose debugging of zsh and source my rc file, I can see that the correct directory is being found for the script:

```
# source antidote
source $HOME/.local/antidote/antidote.zsh
+.zshrc:37> source /home/afore/.local/antidote/antidote.zsh
# shell prereq
if test -z "$ZSH_VERSION"; then
  shellname=$(ps -p $$ -oargs= | awk 'NR=1{print $1}')
  echo >&2 "antidote: Expecting zsh. Found '$shellname'."
  return 1
fi
+/home/afore/.local/antidote/antidote.zsh:2> test -z 5.0.2

if ! typeset -f __antidote_setup &>/dev/null; then
  autoload -Uz ${0:A:h}/functions/__antidote_setup
fi
+/home/afore/.local/antidote/antidote.zsh:8> typeset -f __antidote_setup
+/home/afore/.local/antidote/antidote.zsh:9> autoload -Uz /home/afore/.local/antidote/functions/__antidote_setup
__antidote_setup
+/home/afore/.local/antidote/antidote.zsh:11> __antidote_setup
/home/afore/.local/antidote/antidote.zsh:11: command not found: __antidote_setup
```

**Comment by mattmc3** [comment]
Thank you for this report. It was a tough bug to track down, but I think I've got it. I'll test a bit more, but then cut the 1.9.0 release with the fix.

**Comment by vaz-ar** [comment]
I got the same error on a RHEL 7 system, looking at the code I understand that it is because my ZSH version is too old, but at no point did I get the message from `__antidote_setup` 
`"antidote: Unsupported Zsh version '$ZSH_VERSION'. Expecting Zsh >5.4.2."`, I get the same output as https://github.com/mattmc3/antidote/issues/138#issuecomment-1614712660

I can open a new issue for that if necessary

**Comment by mattmc3** [comment]
I've added an earlier Zsh version check for the upcoming 1.9.1 release to address this.
