### ISSUE TITLE
"function definition file not found" on update

### ISSUE THREAD

**Issue by mathomp4** [mattmc3/antidote#139]
I noticed this today when I ran my every-so-often `antidote update`:

```console
❯ antidote update
Updating bundles...
antidote: checking for updates: https://github.com/marlonrichert/zsh-autocomplete
antidote: checking for updates: https://github.com/romkatv/powerlevel10k
antidote: checking for updates: https://github.com/romkatv/zsh-defer
antidote: checking for updates: https://github.com/zdharma-continuum/fast-syntax-highlighting
antidote: checking for updates: https://github.com/zsh-users/zsh-autosuggestions
antidote: checking for updates: https://github.com/zsh-users/zsh-history-substring-search
Waiting for bundle updates to complete...
Bundle updates complete.
Updating antidote...
Antidote self-update complete.

antidote-update:46: __antidote_core: function definition file not found
antidote version 1.8.8 (0b29bea)
```

Now, I didn't capture it here, but it seems to update all the plugins fine. But it can't seem to update itself?

Now, the thing is I should be at v1.8.9 because the repo I have cloned seems to say it is there:
```console
❯ cd ~/.antidote
❯ git remote update --prune
❯ git diff v1.8.9
❯
```
but antidote seems to say it is still 1.8.8.

**Comment by mattmc3** [comment]
Hey @mathomp4, thanks for your bug report. I can confirm this is an issue in the transition from 1.8.8 to 1.8.9. Your antidote install did successfully self-update, it just did not properly reload itself in your current Zsh session. There shouldn't be a problem with your antidote install, and if you open a new Zsh session and type `antidote --version` you should get `antidote version 1.8.9 (0b29bea)` and all should be well with the install. However, this is a bad user experience, so thank you for the bug report and I'll see if I can cut a quick fix for those still on 1.8.8 who haven't upgraded yet.
