### ISSUE TITLE
Willing to set up github sponsorship to let people show appreciation?

### ISSUE THREAD

**Issue by kohane27** [mattmc3/antidote#145]
Hello @mattmc3 , hope you're doing well.

I'm wondering if you're willing to set up github sponsorship to let people like me to show some appreciation of your work? I benefit a lot from your `antidote`, `zephyr`, `zdotdir`, `zsh_unplugged` etc, and would like to contribute a few coffees to show my appreciation.

Thank you again for all the hard work you do for the `zsh` community!

**Comment by mattmc3** [comment]
Hey @kohane27! Thank you so much for the kind words. I have (briefly) considered adding a `FUNDING.yml` for certain projects, but when it comes down to it I much prefer to keep a clean separation between my fun hobbies and my paid work. Your digital words of gratitude is reward enough, but if you or anyone else wants to show appreciation with a donation to the [Electronic Frontier Foundation](https://supporters.eff.org/donate), their work to defend civil liberties in a digital world is worth supporting.
