### ISSUE TITLE
Change log on update?

### ISSUE THREAD

**Issue by Spirarel** [mattmc3/antidote#148]
Is there a way to view an aggregate change log when we run update? I seem to remember oh-my-zsh doing this and it was a welcome feature. Is that already replicable somehow or would it need some engineering effort?
<img width="862" alt="Screenshot 2023-08-07 at 7 36 56 PM" src="https://github.com/mattmc3/antidote/assets/10119394/7a5aeb22-8329-424a-9d0b-bed381025cbf">

**Comment by mattmc3** [comment]
That's a clever idea. I already know the old and new git commit SHA for an update, so perhaps it would be as easy as:

```zsh
oldsha=d6b5952; newsha=86ded5a
git log --oneline --ancestry-path ${oldsha}~1..${newsha}
```

But OMZ [has quite the large script to accomplish this](https://github.com/ohmyzsh/ohmyzsh/blob/master/tools/changelog.sh), so I don't want to make any promises.
