### ISSUE TITLE
A question with the backquote and apostrophe syntax in antidote-load man page

### ISSUE THREAD

**Issue by LuckyWindsck** [mattmc3/antidote#153]
Hi, I am new to **antidote**.
When I was reading the man page of `antidote-load`, I found that you are using the **backquote and apostrophe** format.
I am wondering if this is intended or just a typo.

https://github.com/mattmc3/antidote/blob/46d54d4fd7ec44e0d94c985debed582878fafe70/man/man1/antidote-load.1#L37
https://github.com/mattmc3/antidote/blob/46d54d4fd7ec44e0d94c985debed582878fafe70/man/man1/antidote-load.1#L46

If I execute `zstyle` command in this way, zsh will throw an error: <code>unmatched`</code>.

**Comment by LuckyWindsck** [comment]
I've just investigate the source code, and only the man page of `antidote-load` use this syntax.

<details>
  <summary>Screenshot of search result</summary>
  <img width="743" alt="image" src="https://github.com/mattmc3/antidote/assets/24631178/02156724-db26-450a-9ed0-3800089254c5">
</details>

However, I found that the man page of `antidote-bundle` also contains the usage of `zstyle` command, and it's generated correctly.
I am not familiar with `pandoc`, the software you used to generate man page with markdown file. Should we escape the single quote in markdown file?

<details>
  <summary>Screenshot of search result</summary>
  <img width="987" alt="image" src="https://github.com/mattmc3/antidote/assets/24631178/d3648ef1-199f-4dfa-bb0d-233697e7bda6">
</details>

**Comment by mattmc3** [comment]
Great question. I pretty much live in the markdown versions of the man pages and let pandoc make the actual man format. Of course, pandoc doesn't perfectly support a conversion from markdown to man, so I think it came out wrong unless I escaped the single ticks, and must've missed some. I'll fix it for 1.9.3. Great catch.

**Comment by mattmc3** [comment]
v1.9.3 was released.
