### ISSUE TITLE
`antidote install` should be aware of my custom plugins txt file location

### ISSUE THREAD

**Issue by boldandbrad** [mattmc3/antidote#161]
By default `antidote install plugin` appends the plugin the plugin file located at `~/.zsh_plugins.txt`. 

However, I prefer to keep my plugin txt file elsewhere. I understand that `antidote install` allows you to pass the correct path as an additional argument, but this is a hassle when I just want to install and move on. 

It would be nice if I could set an ENV variable like `ANTIDOTE_PLUGIN_FILE` or something to tell antidote to always install / load from that file location.

My apologies if this is already possible, I could not find a solution in the docs.

**Comment by mattmc3** [comment]
Per the docs:

> The default bundle file is `${ZDOTDIR:-$HOME}/.zsh_plugins.txt`. This can be overridden with the following `zstyle`:
> `zstyle ':antidote:bundle' file /path/to/my/bundlefile`

Add that style to your .zshrc prior to sourcing antidote. I'll be sure to include that same verbiage in the help for `antidote install -h` for the next release.

**Comment by boldandbrad** [comment]
Idk how I didn't catch that. Thank you!

**Comment by mattmc3** [comment]
No worries! It wasn't in the "antidote install" part of the docs, so I'm glad to have the callout so I can add it for the 1.9.4 release.
