### ISSUE TITLE
[Question] Will Antidote maintain the plugins up to date with their remote repositories?

### ISSUE THREAD

**Issue by obvionaoe** [mattmc3/antidote#17]
Basically the title. Will Antidote be able to update the plugins by itself or will I need to manually do it?

Thanks

**Comment by mattmc3** [comment]
The `antidote update` command updates antidote itself, and all your plugins managed by antidote.

In addition, I have a planned feature for pinned SHAs that would allow you to prevent a repo from updating, but it’s not yet implemented. Generally I would assume you’d want the latest, which is simply `antidote update`.

**Comment by obvionaoe** [comment]
That's perfect for my use case! Thanks!
