### ISSUE TITLE
Local variable in plugin doesn't work

### ISSUE THREAD

**Issue by chungweileong94** [mattmc3/antidote#172]
I was trying to setup this theme https://github.com/vercel/zsh-theme. However, I notice that all the `local` variables doesn't work for some reason.

**Comment by mattmc3** [comment]
This is related to the plugin you're using and not anything antidote is doing. Try opening an issue with the plugin author.

**Comment by chungweileong94** [comment]
Sure, actually it's not really (or I'm not sure) something related to a specific plugin. If we create a `local` variable, it just doesn't work, the plugin that I shared is just an example.
