### ISSUE TITLE
incorrect autoload instructions

### ISSUE THREAD

**Issue by visigoth** [mattmc3/antidote#173]
`getantidote.github.io` has autoload instructions for antidote, but they are incorrect, at least for v1.9.4. also, `getantidote.github.io` differs from the installation instructions in the github repository's README, which advises to lazily `source /path/antidote.zsh` instead.

i prefer autoload since that would make `antidote` a valid command for any shell, rather than only sourcing `antidote.zsh` when the plugins need to be refreshed.

i installed antidote v1.9.4 via homebrew. `ls -l $(brew --prefix)/opt/antidote/share/antidote` shows the following:

```
.rw-r--r-- shaheen staff 517 B Sun Dec  3 10:50:21 2023  antidote.zsh
drwxr-xr-x shaheen staff 960 B Sun Dec  3 10:50:21 2023  functions
```

the web site says antidote can be autoloaded from this directory, but the function definition file is actually installed to the `functions` directory. fixing `fpath` to point here seems to work, though this file has different logic than `antidote.zsh`, so i'm not sure what the "right" way to load antidote is.

**Comment by mattmc3** [comment]
Thanks for opening this issue. I've updated the autoload install instructions on the site here: https://getantidote.github.io/install
