### ISSUE TITLE
pr command missing on some systems

### ISSUE THREAD

**Issue by mbsmith** [mattmc3/antidote#174]
In antidote-script line:114 the pr command piped to does not exist for me, as well as other systems.  In my case it's Alpine Linux.  It's notably a part of coreutils however not busybox, and some others.  As it seems to work fine without it we could possibly just remove it?

Also great work on the project!  Keep up the good work.

**Comment by mattmc3** [comment]
Thanks @mbsmith. I agree - reliance on the existence of `pr` is unnecessary. I'm cutting a 1.9.5 release with this fix.
