### ISSUE TITLE
Change output to green rather than bright green?

### ISSUE THREAD

**Issue by eggbean** [mattmc3/antidote#181]
This is a minor thing, but is there a way to change the output colour from bright green to green? This is just so that it fits in better with the rest of the output from my update scripts, but it's not important.

**Comment by mattmc3** [comment]
I'm open to adding ways to customize this. I would typically do this with something like a `zstyle`. So, maybe something like this:

```zsh
zstyle ':antidote:update' color success $(tput setaf 2)
```

**Comment by eggbean** [comment]
Yes, that sounds good.

**Comment by eggbean** [comment]
Cool, thanks!
