### ISSUE TITLE
Add a way to benchmark the loading time of installed plugins

### ISSUE THREAD

**Issue by devnoname120** [mattmc3/antidote#183]
It would be tremendously useful if antidote had a mode or an option for measuring how much time each plugin takes to load in order to help troubleshoot/optimize one's list of plugins.

Something basic (e.g. single run) would already go a long way!

**Comment by mattmc3** [comment]
Are you familiar with `zprof`? You can simply temporarily add `zmodload zsh/zprof` to the top of your `.zshrc` and `zprof` at the end to get profiling information. For more advanced profiling, you can also use `XTRACE`.

While it's not the most user-friendly output, it's pretty good for this purpose and well known, and there's lots of examples on the web of this kind of tuning:
- https://blog.jonlu.ca/posts/speeding-up-zsh
- https://www.bigbinary.com/blog/zsh-profiling
- https://www.reddit.com/r/zsh/comments/q5e2du/ann_zshbench_benchmark_for_interactive_zsh/
- https://stevenvanbael.com/profiling-zsh-startup
- https://esham.io/2018/02/zsh-profiling
- https://blog.mattclemente.com/2020/06/26/oh-my-zsh-slow-to-load/

When viewing the output, you'll want to remember that parts of your config that source other parts are aggregated, which means that times may appear to be double counted. For example, if you use `antidote load`, its time is the sum of all the time your plugins take, not simply the actual time `antidote load` itself takes.

As far as adding a feature to antidote, I don't think it adds much to re-implement features that already exist, even if there's a more streamlined way to show that data.
