### ISSUE TITLE
Local plugins

### ISSUE THREAD

**Issue by obvionaoe** [mattmc3/antidote#19]
Is there a way to use antidote with local plugins? I know I could just source it directly but I'd like to be able to use antidote to manage my local plugins

Thanks

**Comment by mattmc3** [comment]
You sure can. "repos" in your plugins file that start with a "/" are assumed to be local paths. You can even use environment variables that are set prior to initializing Antidote to avoid hardcoding a path. To do that, simply use the `envsubst` command (assuming your distribution has it). So, imagine you have a plugins file like this:

```properties
# $ZDOTDIR/.zsh_plugins.txt

# other plugins
rupa/z
ohmyzsh/ohmyzsh path:plugins/extract

# your local plugin
$HOME/.config/zsh/path/to/myplugin

# or, use ZSH's dotdir
$ZDOTDIR/my_other_plugin
```

And then in your .zshrc, just use `envsubst` to replace the environment variables:

```zsh
#.zshrc
zhome=${ZDOTDIR:-$HOME}
if [[ ! $zhome/.zsh_plugins.zsh -nt $zhome/.zsh_plugins.txt ]]; then
  [[ -e $zhome/.zsh_plugins.txt ]] || touch $zhome/.zsh_plugins.txt
  (
    source $zhome/.antidote/antidote.zsh
    envsubst <${ZDOTDIR:-~}/.zsh_plugins.txt | antidote bundle >$zhome/.zsh_plugins.zsh
  )
fi
```
