### ISSUE TITLE
I have a request/ Learning how to use Antidote, Zsh, and config files

### ISSUE THREAD

**Issue by oddsito** [mattmc3/antidote#193]
I understand people are too busy being intelligent and productive, and smart.
And im glad it works that way.

I have only 1 request since 1-2 year ago. 
Is it possible for you to make a video, or work along someone in order to make a video and teach others how to use Zsh, and Antidote itself?

I am still using antigen because my neurons are not so developed, i am not a very smart person, i had to follow a 5 year old video // https://www.youtube.com/watch?v=ZUhAgJPlzvg

In order to learn how to use antigen, and i had to see many videos about zsh, and oh-my-zsh in order to actually make basic, small progress.

I have been visiting your website since 2-3 years ago, hoping to be able to migrate to Antibody, every 3-4 months i read the installation and usage instructions, all of the information at https://getantidote.github.io/ website, but my mind is unable to process the instructions for some reason.
I know this is completely irrelevant to you, but could you show us less intelligent people and new Linux users how to use your software with a Video? That way we can understand better, copy and follow someone that knows more.
You've probably seen the huge, massive amount of people that are currently migrating from Windows to Linux, doing this would surely help millions of new users, and attract users to you. Pretty Pleaaase ♥?

**Comment by mattmc3** [comment]
I'm not a YouTuber. The content I'm good at creating is in code and text form, not video. Any videos I make are unlikely to be very helpful compared to someone who is actually good at that. That's not my artistic medium.

I understand that antidote and Zsh in general can be really tricky to learn and the documentation dense. Have you found [the code examples](https://github.com/getantidote/zdotdir)? I find that seeing actual code is more helpful when I'm learning, but everyone learns differently. If you learn best by watching videos, why not reach out to some of the popular YouTubers with a proposal to do something like a Zsh plugin manager bake-off? My quick search found a few content producers that frequently have Zsh content on their channels:

- https://www.youtube.com/@dreamsofautonomy
- https://www.youtube.com/@BrodieRobertson
- https://www.youtube.com/@DistroTube

(Note: none of these are endorsements, just channels I found searching for Zsh content producers.)

Alternatively, if you aren't finding what you need, start with something more popular where there's lots of video content, like Oh-My-Zsh. The [Fish shell](https://fishshell) is also much easier to learn and use than Zsh, and there's [lots of video content](https://www.youtube.com/watch?v=8GN9D-OnG-A). I highly recommend that for new learners.

If you do use Zsh+antidote and run into trouble and have a specific question, you can ask here, or the [Zsh subreddit](https://www.reddit.com/r/zsh).
