### ISSUE TITLE
Aliases not working

### ISSUE THREAD

**Issue by CHE1RON** [mattmc3/antidote#197]
Hey there!

First of all, I really liked this as a starting point for `antidote` configuration. However, I stumbled over the `.aliases` file being referenced in `.zsh_plugins.txt` giving me `function definition file not found`, and thus being unable to use the project 🤔 

Any ideas on this are much appreciated! 🙏

**Comment by mattmc3** [comment]
What is sounds like you want is to include local files / folders as plugins rather than git repos. No problem! That's supported in antidote, but in order to do that you need to put the full path in your .zsh_plugins.txt, or use a variable like so:

```zsh
# ~/.zsh_plugins.txt
# This will fail because antidote thinks you want a repo:
.aliases

# This will succeed because you were explicit with a path:
~/.aliases

# This will also succeed because you used a variable:
$ZDOTDIR/.aliases
```

**Comment by CHE1RON** [comment]
Alright, thanks so much!
