### ISSUE TITLE
How can specify a commit I want to use for a plugin?

### ISSUE THREAD

**Issue by josevelaz** [mattmc3/antidote#205]
There is a current bug in zsh-autocomplete that causes a freeze when typing a command, and the [current workaround it](https://github.com/marlonrichert/zsh-autocomplete/issues/736#issuecomment-2232428532) is to revert back to a previous commit.

I see you are able to specify a branch for the plugin but not a commit hash.

Also, I cant seem to find any documentation as to where the git repos are cloned to to be able to manually switch the commit

**Comment by josevelaz** [comment]
DUplicate issue. https://github.com/mattmc3/antidote/issues/1

**Comment by mattmc3** [comment]
Here's how you can revert back to a specific commit until this feature is implemented:

```zsh
# make sure antidote is loaded, and then set these vars to whatever you need
source /path/to/antidote.zsh
GIT_WORKING_SHA=cfc3fd9a75d0577aa9d65e35849f2d8c2719b873
GIT_DIR=$(antidote path marlonrichert/zsh-autocomplete)

# revert Zsh plugin managed by antidote to a prior SHA
git -C "$GIT_DIR" fetch --unshallow
git -C "$GIT_DIR" checkout $GIT_WORKING_SHA
```
