### ISSUE TITLE
Nix Package Manager support

### ISSUE THREAD

**Issue by JDRanpariya** [mattmc3/antidote#21]
It would be nice to have it on nix pkgs also what about benchmarks with zinit? it has some turbo mode and the say it's five time faster.

**Comment by mattmc3** [comment]
I'm not sure what's involved in making a nix package, but PRs/suggestions welcome.

As far as benchmarks go, we do have some and antidote comes out ahead of zinit: https://github.com/romkatv/zsh-bench/blob/master/doc/linux-desktop.md

If there are other standard benchmarks tools out there where we want to use to compare, let me know but currently romkatv's stuff seems to be the newest de facto standard.
