### ISSUE TITLE
Solving `command not found: compdef`

### ISSUE THREAD

**Issue by devnoname120** [mattmc3/antidote#24]
`antidote` requires `compinit` for completions to work.

Add the following to the top of your `~/.zshrc` if it's missing:

```shell
autoload -Uz compinit && compinit
```

**Comment by mattmc3** [comment]
Is this something you're suggesting be added to the antidote docs?

**Comment by devnoname120** [comment]
@mattmc3 I think so! I wasn't too sure where to add it exactly so I eventually just created an issue so that it's indexed by search engines.

Also it would be great if `antidote load` could warn if `autoload -Uz compinit && compinit` wasn't run.

**Comment by mattmc3** [comment]
While that feature would be easy to implement, and not a bad idea overall, the more I think on it the more I'm convinced antidote needs to stay in its lane and stick to providing great plugin-management features and not extras that people then need to override if they want to go a different way. I know other projects like Znap take a different approach and have prompt features, etc.

My goal with antidote is to let people compose their ideal Zsh experience through plugins, so my recommendation for completions would be to use things like [zephyr](https://github.com/mattmc3/zephyr) or [prezto](https://github.com/sorin-ionescu/prezto/tree/master/modules/completion).

However, I did update the docs to show how to add completions. Hope that will suffice: https://getantidote.github.io/completions
