### ISSUE TITLE
Support end-of-line comments `#`

### ISSUE THREAD

**Issue by devnoname120** [mattmc3/antidote#25]
I had some comments in this form in my `~/.zsh_plugins.txt` file when I migrated from `antigen`:

```
ohmyzsh/ohmyzsh path:plugins/git # useful git completions
```

The plugins didn't load and with `set -x` I figured out that there was an expansion issue. I eventually figured out that the culprit was the lack of support for trailing comments.

I would suggest to support them. One way could be to filter `bundle_str` to remove `#[^\n]*$` before splitting into an associative array.

**Comment by mattmc3** [comment]
That's a great idea, and worthwhile feature.

**Comment by mattmc3** [comment]
Fixed in 1.2, which was just released.

**Comment by devnoname120** [comment]
@mattmc3 Great thank you!
