### ISSUE TITLE
Comment out the ~/.zsh_plugins.txt file while removing the plugin

### ISSUE THREAD

**Issue by yyy33** [mattmc3/antidote#30]
After configuring, I can now install the plugin using the antidote install command, which will automatically configure the ~/.zsh_plugins.txt file, and then when I remove the plugin using antidote purge, ~/.zsh_plugins.txt is not modified, so when I restart zsh after removing the plugin, it is So when I restart zsh after removing the plugin, the plugin I removed will be automatically cloned locally and run again, I think it should make sense to comment ~/.zsh_plugins.txt file when antidote purge

Translated with www.DeepL.com/Translator (free version)

**Comment by mattmc3** [comment]
I'd rather leave it to the user to manage their own ~/.zsh_plugins.txt file. The purge command will remove the cloned repo, but the user will need to find the line in ~/.zsh_plugins.txt to comment out or remove it. I will add a message when executing the `purge` command that reminds the user they may want to remove the plugin from this file as well. I've added the comment already to the dev branch. It should go out with v1.3.0.

**Comment by mattmc3** [comment]
I've reconsidered. Rather than removing the plugin, I can comment it out. I've got a feature branch now for this functionality. If you are open to testing it out @yyy33 I'd consider merging it in.

**Comment by mattmc3** [comment]
Fixed in 1.6
