### ISSUE TITLE
Support with brew.sh

### ISSUE THREAD

**Issue by singh-narender** [mattmc3/antidote#33]
I think one liner explain it very well.

**Comment by mattmc3** [comment]
Fair enough. Looks like antigen and antibody did, so it makes sense for antidote to follow suit.

- https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/antibody.rb
- https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/antigen.rb

**Comment by mattmc3** [comment]
https://github.com/Homebrew/homebrew-core/pull/108168

**Comment by mattmc3** [comment]
1.4.0 failed CI with homebrew. 1.4.1 (hopefully) fixes issues and tweaks the man pages.

https://github.com/Homebrew/homebrew-core/pull/108200

**Comment by mattmc3** [comment]
Updated to 1.6.4. Still waiting... 14 newer, 25 older so I'd guess we're about half way there. They still have quite the backlog from July, so we just gotta be patient. Another 4-6 weeks, tops.

https://github.com/Homebrew/homebrew-core/pulls?q=is%3Apr+is%3Aopen+label%3A%22new+formula%22

**Comment by mattmc3** [comment]
This was merged over the weekend. `brew update && brew upgrade; brew install antidote`
