### ISSUE TITLE
add documentation on AUR package

### ISSUE THREAD

**Issue by getchoo** [mattmc3/antidote#38]
i recently packaged this project on the [AUR](https://aur.archlinux.org/packages/zsh-antidote), and i think it would be a good to a section with it next to brew (as mentioned in #33) and other package managers to be supported in the future

**Comment by mattmc3** [comment]
I've had to make some updates to antidote to support older versions of Zsh to pass CI for homebrew. Once I get the homebrew installer merged, if you could update the AUR to whatever version we land on (hopefully 1.5), then I'll update the docs to refer to both and close out both issues. Thanks for doing this!

**Comment by mattmc3** [comment]
Thanks for submitting this issue. Now that homebrew has been merged, I've added the `yay` install instructions on the site for the AUR. Let me know if there's a better way to communicate install instructions with Arch users.

https://getantidote.github.io/install

**Comment by getchoo** [comment]
i would change the term "plugin manager" to "package manager" and the package name for yay to `zsh-antidote` (there was a naming conflict with [this](https://www.antidote.info/en/) writing assistance software)
