### ISSUE TITLE
antidote load help has incorrect zstyle command

### ISSUE THREAD

**Issue by danielparks** [mattmc3/antidote#40]
In the documentation for `antidote load`, it shows the following command:

> `zstyle -s ':antidote:static' file $staticfile`

The `-s` is used for querying, not setting. It should be:

> `zstyle ':antidote:static' file $staticfile`

PR incoming.

**Comment by mattmc3** [comment]
Thanks! Copy/paste error. Happy to approve a PR.

**Comment by danielparks** [comment]
Rad. Yeah, I probably wouldn't have even noticed if I used zstyle more often. Thanks for the quick turnaround!
