### ISSUE TITLE
Some ohmyzsh plugin does not work

### ISSUE THREAD

**Issue by damnever** [mattmc3/antidote#49]
Such as:
```
ohmyzsh/ohmyzsh path:plugins/fd
```
antidote: no init file detected in '/Users/x/Library/Caches/antidote/ohmyzsh/ohmyzsh/plugins/fd'.

**Comment by mattmc3** [comment]
OMZ's fd plugin isn't really a plugin - it has no fd.plugins.zsh file. Instead, it provides additional completions (an `_fd` file). For bundles like this, you want to use the `kind:fpath` annotation.

```zsh
% # this is what you're trying, but it's not a plugin bundle
% antidote bundle ohmyzsh/ohmyzsh path:plugins/fd
antidote: no init file detected in '$ANTIDOTE_HOME/ohmyzsh/ohmyzsh/plugins/fd'.

% # this is what you want for completion bundles - kind:fpath
% antidote bundle ohmyzsh/ohmyzsh path:plugins/fd kind:fpath
fpath+=( $ANTIDOTE_HOME/ohmyzsh/ohmyzsh/plugins/fd )
```

Be sure you are running `compinit` or a compinit plugin (like `antidote bundle belak/zsh-utils path:completion`) AFTER you bundle omz's `fd`, or else your completions won't be properly initialized.
