### ISSUE TITLE
Commands are not working

### ISSUE THREAD

**Issue by manuelcattelan** [mattmc3/antidote#54]
Commands like antidote update or antidote purge are not working as expected.

Here's my .zshrc:
```
# drive config with antidote
ANTIDOTE_HOME=$ZDOTDIR/.zplugins
ANTIDOTE_DIR=$ZDOTDIR/.antidote
 
zstyle ':antidote:bundle' use-friendly-names 'yes'
zstyle ':antidote:bundle' file $ZDOTDIR/.zplugins.txt
 
zhome=${ZDOTDIR:-$HOME}
# load antidote
if [[ ! $ZDOTDIR/.zplugins.zsh -nt $ZDOTDIR/.zplugins.txt ]]; then
  [[ -e $ANTIDOTE_DIR ]] \
    || git clone --depth=1 https://github.com/mattmc3/antidote.git $ANTIDOTE_DIR
  (
    source $ANTIDOTE_DIR/antidote.zsh
    antidote bundle <$ZDOTDIR/.zplugins.txt >$ZDOTDIR/.zplugins.zsh
  )
fi
source $ZDOTDIR/.zplugins.zsh
 
autoload -Uz $zhome/.antidote/functions/antidote
```

Every command returns:
```
antidote:10: command not found: __antidote_main
```

**Comment by mattmc3** [comment]
I'm interested in exploring a bit why this isn't working, but I bet you just want to get back to good. Let's do that the simple way and just have you re-clone antidote:

```zsh
ANTIDOTE_DIR=${ZDOTDIR:-~}/.antidote
[[ -d $ANTIDOTE_DIR ]] && rm -rf $ANTIDOTE_DIR
git clone --depth=1 https://github.com/mattmc3/antidote.git $ANTIDOTE_DIR
zsh
```

**Comment by manuelcattelan** [comment]
I have already clean installed antidote but this doesn't seem to work either. If you need more information I'll be more than happy to provide them, I wasn't too sure about what you'd need to investigate the issue.

**Comment by mattmc3** [comment]
@manuelcattelan - I'm so sorry this latest release caused an issue for you. After a little more research, I see where the problem was and have pushed a fix. Can you try the script above again? If that works for you, I'll tag a new release.

**Comment by AnthonyEnr1quez** [comment]
@mattmc3 The change you just pushed fixed this issue for me!

**Comment by mattmc3** [comment]
@AnthonyEnr1quez - Awesome! Thanks for the assist. Sorry for the trouble. I'll tag a release.

**Comment by mattmc3** [comment]
@manuelcattelan - Let me know if I need to re-open this issue, but pretty sure this bug is squashed.

**Comment by manuelcattelan** [comment]
@mattmc3 - Yup the fix works, you can tag a new release and don't worry for the issue. Thanks for your valuable work!
