### ISSUE TITLE
Not zsh_plugins.txt, but zsh directives to list plugins?

### ISSUE THREAD

**Issue by wookayin** [mattmc3/antidote#63]
Personally I don't like the use of `~/.zsh_plugins.txt` file, because it doesn't allow flexible configuration/listing of plugins (i.e. DSL); for instance, we would want to load or activate some plugins conditionally. Other plugin managers like `zsh` supports `zgen load` directive(commands) to list the plugins.

e.g.
```
if is-at-least 5.4; then                                                
  # p10k's minimum zsh requirement is 5.1 but we require zsh 5.4+,  
  # because without the instant mode initialization is slower than pure.
  zgen load romkatv/powerlevel10k 'powerlevel10k.zsh-theme'
else
  # zsh theme: pure (For OLD zsh)
  zgen load mafredri/zsh-async
  zgen load sindresorhus/pure
fi
```

Is something like this an option to be considered?

**Comment by mattmc3** [comment]
> Personally I don't like the use of ~/.zsh_plugins.txt file, because it doesn't allow flexible configuration/listing of plugins

Sure it does. We just have to implement the feature in the DSL. And it may surprise you to learn - it's already implemented as an annotation called `conditional`, I just haven't documented it yet. I use it to load macOS specific plugins. The annotation works like this:

```zsh
# .zshrc
# you have to define a function somewhere in your config before loading antidote
functions is_macos {
  [[ $OSTYPE == darwin* ]] && return 0 else return 1
}

...
antidote load
```

You can write a function in your environment that returns 0 for success, and any other value for failure, and then in your `.zsh_plugins.txt` file:

```zsh
zshzoo/macos conditional:is_macos
```

In your example, you just simply write a function that tests `is-at-least 5.4`. I will say though - 5.4 came out in 2017. I suspect you're not likely to run into this problem on any modern system, but the feature is there if you need it.

**Comment by wookayin** [comment]
Thanks!  It's good to know that the DSL of antidote (zsh_plugins.txt) actually supports conditional annotations. `is-at-least` was just an example (yes, as of 2022 we can drop the support) but `is_macos` could have been a better example. Although it might be just a slightly less expressive than allowing arbitrary zsh scripts, but with this it looks like to cover most of the practical use cases. 

One small downside I still see with this external plugin_files is that I have to manage the list of plugin in a separate file, lacking locality a bit. If I'd like to put everything in a single file, would it be fine use `antidote bundle` instead of `antidote load`? -- for instance

```
antidote bundle <<EOF
zsh-users/zsh-completions
EOF
```

which can be piped to `$staticfile` and then sourced.

**Comment by mattmc3** [comment]
Yes, that’s fully supported. Using a HERDOC for antidote bundle works very well actually. Also, if performance isn’t your primary concern, you can also skip the static file altogether and load all your plugins dynamically just like you could in antibody (https://getantidote.github.io/migrating-from-antibody). This also keeps everything in .zshrc.

**Comment by wookayin** [comment]
I see, my apologies I hadn't read the documentation more in detail. https://getantidote.github.io/migrating-from-antigen also describes the dynamic loading mechanism and HEREDOC example;  antidote looks really cool as it supports both of static loading (for performance) and dynamic loading (for flexibility)!  Thank you very much again.

**Comment by wookayin** [comment]
@mattmc3 suggest another alternative way to list plugins in a single file: https://github.com/mattmc3/antidote/issues/65#issuecomment-1248718991
