### ISSUE TITLE
Simpler bundle directory name

### ISSUE THREAD

**Issue by wookayin** [mattmc3/antidote#66]
Currently bundle plugins stored in `$ANTIDOTE_HOME` have the following directory format:

```bash
# for romkatv/powerlevel10k
https-COLON--SLASH--SLASH-github.com-SLASH-romkatv-SLASH-powerlevel10k
# for sorin-ionesc/prezto
https-COLON--SLASH--SLASH-github.com-SLASH-sorin-ionescu-SLASH-prezto
```

This looks quite verbose and not easy to navigate when one needs to debug a specific bundle plugin. (for instance, it's hard to `cd` to) How about having bundledir as a simpler name, say `namespace/repository`?

`antidote bundle namespace/repository` implies the repository is hosted at `github.com`, so in this case having the bundle directory as `$ANTIDOTE_HOME/namespace/repository` would make a sense and be pretty simple.

**Comment by wookayin** [comment]
Oh wait, it's already there. Take a look at `__antidote_bundledir` in `antidote.zsh` for how it's currently implemented. 

This is the option:
```
zstyle ':antidote:bundle' use-friendly-names on
```

I couldn't find it in the documentation; so hopefully somebody will find this useful.  BTW why don't we consider this as a default behavior?

**Comment by mattmc3** [comment]
It’s not the default because this project started as a drop in replacement for antibody when it was deprecated, so it mimics its defaults. I too prefer the friendly names zstyle for my own config, but felt it was important to create a smooth transition for antibody users.
