### ISSUE TITLE
Is it possible to run commands after cloning or installation?

### ISSUE THREAD

**Issue by mel0n0** [mattmc3/antidote#78]
Hello again! I have a feature request to run a command after cloning or installing a plugin, similar to `atclone` with [zinit](https://github.com/zdharma-continuum/zinit#command-execution-after-cloning-updating-or-loading), or tag `hook-build` of [zplug](https://github.com/zplug/zplug#3-tags-for-zplug).

I briefly looked at the antidote's documentation and not sure if it has any relevant features.

For me, I want to automatically add a symlink inside the plugin directory after it is installed, rather than doing it manually. Is there a viable way?

Related: https://github.com/DFurnes/purer/issues/12

**Comment by mattmc3** [comment]
I'll close this for now and track it here: https://github.com/mattmc3/antidote/issues/12

**Comment by LuckyWindsck** [comment]
> @mattmc3: None of the antigen family of plugin managers (of which I consider antidote to be a part of) have these kinds of hooks, however [I'm not opposed to it](https://github.com/mattmc3/antidote/issues/12), it's just not on any near term roadmap for antidote.

Sorry for bothering a closed issue. I am not sure "these kinds of hooks" you mentioned means the [zsh hook functions](https://zsh.sourceforge.io/Doc/Release/Functions.html#Hook-Functions) or a more general hook function (https://github.com/mattmc3/antidote/issues/12) for plugin manager.

If you meant hook function for plugin manager, **antigen** did implement a [antigen-add-hook](https://github.com/zsh-users/antigen/blob/64de2dcd95d6a8e879cd2244c763d99f0144e78e/src/ext/ext.zsh#L6-L50), and I have used it to implement hooks that will be executed pre-apply & post-apply (https://github.com/LuckyWindsck/dotfiles/issues/1#issuecomment-1684739810).

**Comment by mattmc3** [comment]
@LuckyWindsck - it's not well documented, but a hook feature exists in the form of `pre` and `post` annotations. For example:

```zsh
$ antidote bundle zsh-users/zsh-autosuggestions pre:func_do_before post:func_do_after
func_do_before
fpath+=( $ANTIDOTE_HOME/zsh-users/zsh-autosuggestions )
source $ANTIDOTE_HOME/zsh-users/zsh-autosuggestions/zsh-autosuggestions.plugin.zsh
func_do_after
```

It's up to you to write the pre/post functions (ie: `func_do_before` and `func_do_after` in this example). There aren't hooks for pre/post clone and pre/post update, however, though I'm not sure they're strictly useful. Never having needed or used antigen's hook feature myself, and with antibody not having anything like it, I didn't want to go too deep down this rabbit hole without a user who could properly describe what they needed from a feature like this. Let me know if the pre/post annotation is sufficient.
