### ISSUE TITLE
Is there a way to check if a plugin is installed?

### ISSUE THREAD

**Issue by ywpkwon** [mattmc3/antidote#79]
I'm using `zsh-history-substring-search`, which requires key binding.

I saw some codes like this: https://github.com/zsh-users/zsh-history-substring-search/issues/64
```zsh
if zplug check zsh-users/zsh-history-substring-search; then
    bindkey '\eOA' history-substring-search-up
    bindkey '\eOB' history-substring-search-down
fi
```
What would be a good way to do this (checking if a plugin is installed) with `antidote`?

**Comment by mattmc3** [comment]
There's not a specific command, but you could pretty easily use `antidote path` for this. Send the txt to /dev/null and it accomplishes the same thing:

```zsh
if [[ antidote path zsh-users/zsh-history-substring-search >/dev/null ]]; then
  bindkey '\eOA' history-substring-search-up
  bindkey '\eOB' history-substring-search-down
fi
```

**Comment by ywpkwon** [comment]
Oh, one more question! 
The command `antidote path zsh-users/zsh-history-substring-search >/dev/null` works well in the terminal.
However, how I can use that in `.zshrc`?

Should I do 
- `if [[ $(antidote path ...) ]]; then`
- `if [[ $(antidote path ...) >/dev/null ]]; then`
- `if [[ eval "$(antidote path ...)"; then` or something?

Sorry, I'm so familiar with the shell scripting.

**Comment by mattmc3** [comment]
@ywpkwon - Oh man, I apologize. I'm so used to typing `if [[ ... ]]` that I missed the syntax error. You don't need `[[ ]]` at all for this type of test:

```zsh
if antidote path zsh-users/zsh-history-substring-search >/dev/null; then
  ...
fi
```
