### ISSUE TITLE
usage example needed for pip autocompletion

### ISSUE THREAD

**Issue by ywpkwon** [mattmc3/antidote#80]
When I was using antigen, the below setup gave me `pip` autocompletion
```zsh
antigen use oh-my-zsh
antigen bundle pip
```

I'm migrating to antidote, and I tried this
```zsh
ohmyzsh/ohmyzsh path:lib                           # these were in tutorial
ohmyzsh/ohmyzsh path:plugins/colored-man-pages     # these were in tutorial
ohmyzsh/ohmyzsh path:plugins/magic-enter           # these were in tutorial
ohmyzsh/ohmyzsh path:plugins/pip                   # is this right?
```

the `pip` is for autocompletion so (I'm guessing) the `path` option may be not proper here, but I have no idea how I can setup properly. How can I import the autocomplete plugin defined in `ohmyzsh/ohmyzsh:plugins/pip` ? (and hopefully not others in that directory).

**Comment by mattmc3** [comment]
The `path:plugins/pip` annotation is correct. You can see what antidote is doing by just running its bundle command:

```zsh
% antidote bundle ohmyzsh/ohmyzsh path:plugins/pip
fpath+=( $HOME/.zplugins/ohmyzsh/ohmyzsh/plugins/pip )
source $HOME/.zplugins/ohmyzsh/ohmyzsh/plugins/pip/pip.plugin.zsh
```

The bundle command sets `fpath`, giving you the completions from the `_pip` file. It also sources the pip.plugin.zsh file from Oh-My-Zsh as well.

**Comment by ywpkwon** [comment]
Thanks for your kind explanation! But I think I'm not getting autocompletion like "pip ins<tab>" thing where I can when using antigen. What would be the reason?

**Comment by mattmc3** [comment]
The only reason I can think of that you wouldn’t have completions is if you didn’t call compinit.

https://github.com/mattmc3/antidote/discussions/74

Antigen may do this for you. Antidote (and antibody) do not.

**Comment by ywpkwon** [comment]
Thanks! It works! You're awesome!
