### ISSUE TITLE
directories.zsh:32: command not found: compdef

### ISSUE THREAD

**Issue by ZhiyuanChen** [mattmc3/antidote#81]
Hi

I'm recently upgrading from antigen to antidote, but encountered the following issue: 

```zsh
antidote/https-COLON--SLASH--SLASH-github.com-SLASH-ohmyzsh-SLASH-ohmyzsh/lib/directories.zsh:32: command not found: compdef
```

**Comment by mattmc3** [comment]
You need to run `compinit` to enable completions. See this discussion: https://github.com/mattmc3/antidote/discussions/74

**Comment by mattmc3** [comment]
As of June 2024, the recommended way of handling OMZ is now to include the new [getantidote/use-omz](https://github.com/getantidote/use-omz) plugin at the TOP of your `.zsh_plugins.txt` file. It handles all OMZ dependency resolution, setting OMZ variables, and deferred completion initialization for OMZ users. No more `compdef` errors!
