### ISSUE TITLE
Automatic Purge options for removed plugins

### ISSUE THREAD

**Issue by fharper** [mattmc3/antidote#83]
It would be nice to have a setting that enables an automatic purge for plugins removed or commented from the plugin file.

**Comment by mattmc3** [comment]
It's not automatic, but you could achieve this pretty easily by running `antidote purge --all; antidote bundle /path/to/.zsh_plugins.txt`, which would start you over fresh.

**Comment by fharper** [comment]
@mattmc3 thanks, I run this when I remove a plugin or do the purge manually with the plugin name, but the important part of this feature suggestion is the automatic :)

**Comment by mattmc3** [comment]
After considering this, I don't want antidote to assume that the user wants to re-clone everything not in their `.zsh_plugins.txt` with any regularity. I swap mine out all the time, and I also have clones in there that are for things other than Zsh.

If someone wants a regular cleanup of their cache, this can be accomplished by making a cron job with this script:

```zsh
#!/usr/bin/env zsh
source /path/to/antidote.zsh
zstyle ':antidote:purge:all' answer 'y'
antidote purge --all
zstyle -d ':antidote:purge:all' answer
antidote bundle <${ZDOTDIR:-$HOME}/.zsh_plugins.txt
```
