### ISSUE TITLE
Homebrew source instructions

### ISSUE THREAD

**Issue by mrienstra** [mattmc3/antidote#85]
The simple version of what lines to add to`.zshrc` in [getantidote/getantidote.github.io _sections/04-install.md?plain=1#L30-L31](https://github.com/getantidote/getantidote.github.io/blob/4ef6ca2/_sections/04-install.md?plain=1#L30-L31) (visible on the website [here](https://getantidote.github.io/#zshrc)) includes:
```
# source antidote
source ${ZDOTDIR:-~}/.antidote/antidote.zsh
```

As per https://formulae.brew.sh/formula/antidote (and CLI output when `antidote` is installed with Homebrew):
```
To activate antidote, add the following to your ~/.zshrc:
    source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh
```

Might be nice to mention this in the docs, to make it a little easier to get up and running when choosing to install with `brew install antidote`?

**Comment by mattmc3** [comment]
Thanks for the suggestion. The docs have been updated.
