### ISSUE TITLE
Not All Plugins Bundle

### ISSUE THREAD

**Issue by aaaaaadrian** [mattmc3/antidote#87]
Preface: Pretty new to all this and moving from Antibody, so I apologize in advance for any dumb question.

I have had a hell of a time getting antidote to even work as a command, but I finally got it working through Homebrew. 

When I bundle my plugins.txt file to be a plugins.zsh file, it omits half of them.

Current plugins.txt file

```
ohmyzsh/ohmyzsh path:plugins/colored-man-pages
ohmyzsh/ohmyzsh path:plugins/command-not-found
ohmyzsh/ohmyzsh path:plugins/wd
ohmyzsh/ohmyzsh path:plugins/alias-finder
ohmyzsh/ohmyzsh path:plugins/macos
ohmyzsh/ohmyzsh path:plugins/colorize

zsh-users/zsh-autosuggestions
zsh-users/zsh-completions
zsh-users/zsh-syntax-highlighting
```

Running this `antidote bundle < ~/.config/.zsh/.zsh_plugins.txt > ~/.config/.zsh/.zsh_plugins.zsh` I get 

```
# antidote cloning ohmyzsh/ohmyzsh...
# antidote cloning zsh-users/zsh-autosuggestions...
# antidote cloning zsh-users/zsh-completions...
# antidote cloning zsh-users/zsh-syntax-highlighting...
```

So when I run `antidote list` I get this

```
https://github.com/ohmyzsh/ohmyzsh                               ~/Library/Caches/antidote/https-COLON--SLASH--SLASH-github.com-SLASH-ohmyzsh-SLASH-ohmyzsh
https://github.com/zsh-users/zsh-autosuggestions                 ~/Library/Caches/antidote/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-autosuggestions
https://github.com/zsh-users/zsh-completions                     ~/Library/Caches/antidote/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-completions
https://github.com/zsh-users/zsh-syntax-highlighting             ~/Library/Caches/antidote/https-COLON--SLASH--SLASH-github.com-SLASH-zsh-users-SLASH-zsh-syntax-highlighting
```

Is there something I am missing?

The end of my .zshrc file (taken from https://getantidote.github.io/install

```
antidote_dir=${ZDOTDIR:-~}/.config/.zsh/.antidote
plugins_txt=${ZDOTDIR:-~}/.config/.zsh/.zsh_plugins.txt
static_file=${ZDOTDIR:-~}/.config/.zsh/.zsh_plugins.zsh

source $(brew --prefix)/opt/antidote/share/antidote/antidote.zsh

# source the static plugins file
source $static_file

# cleanup
unset antidote_dir plugins_txt static_file
```

**Comment by mattmc3** [comment]
Most of your plugins are Oh-My-Zsh plugins, which is fine. But `antidote list` is only going to show you the repositories you've cloned, not the full list of plugins from your plugins.txt. TLDR; if you want to see all the things antidote is going to do you need to look in your static file, and you haven't included that. If you `cat =${ZDOTDIR:-~}/.config/.zsh/.zsh_plugins.zsh`, you should see all the Zsh statements for sourcing your plugins based on your `plugins.txt` file.

From your description, I'm not seeing anything you're doing wrong, and antidote should be working properly for you. Are you having plugins that aren't loading properly? OMZ can be finicky - have you read https://github.com/mattmc3/antidote/discussions/70 ? You may also want to source OMZ's lib directory before using OMZ plugins: `ohmyzsh/ohmyzsh path:lib`

**Comment by aaaaaadrian** [comment]
I added the OMZ lib and I think it's working now.

Trying to organize all my DOTFILES has been confusing, but this is the right step I think.

Thanks so much, I'll close this.
