### ISSUE TITLE
The AUR is no longer building

### ISSUE THREAD

**Issue by NovaViper** [mattmc3/antidote#95]
The AUR package is no longer installing, I get this error now whenever I try to install it with yay on EndeavourOS:

```
==> Validating source files with sha256sums...
    antidote-1.7.1.tar.gz ... FAILED
    0001-no-self-updating.patch ... Passed
==> ERROR: One or more files did not pass the validity check!
 -> error downloading sources: zsh-antidote 
    context: exit status 1 


==> Making package: zsh-antidote 1.7.1-1 (Mon 30 Jan 2023 05:58:39 PM CST)
==> Checking runtime dependencies...
==> Checking buildtime dependencies...
==> Retrieving sources...
  -> Found antidote-1.7.1.tar.gz
  -> Found 0001-no-self-updating.patch
==> Validating source files with sha256sums...
    antidote-1.7.1.tar.gz ... FAILED
    0001-no-self-updating.patch ... Passed
==> ERROR: One or more files did not pass the validity check!
 -> error making: zsh-antidote
```

Will there be a fix for this?

**Comment by mattmc3** [comment]
@NovaViper - These links might be of some use to you to help you troubleshoot.

- https://forum.endeavouros.com/t/faq-aur-package-fails-validity-check-one-or-more-files-did-not-pass-the-validity-check/6751
- https://forum.endeavouros.com/t/whats-wrong-with-aur-tailwindcss-bin/34429

**Comment by NovaViper** [comment]
I have no idea why.. it just suddenly started working again randomly today. I'm going to close this now

**Comment by mattmc3** [comment]
Awesome!

**Comment by getchoo** [comment]
> I don’t maintain the AUR, nor do I use Arch or have a way to test that package. There’s no reason I can see why it would have broken, and am using 1.7.1 daily.
> 
> I believe it was originally setup by @getchoo. Any ideas?

i'm guessing it was related to [this](https://github.blog/changelog/2023-01-30-git-archive-checksums-may-change/)
